[tool.interrogate]
fail-under = 0
verbose = 1
ignore-init-method = true
ignore-init-module = true
ignore-module = true
exclude = [
    "glow.py",
    "main.py",
    "application",
    "tests",
    "dataset/silero_utils.py",
    "dataset/transcribe.py",
    "dataset/forced_alignment/search.py",
    "training/tacotron2_model",
    "training/hifigan/meldataset.py",
    "training/hifigan/models.py",
    "synthesis/vocoders/hifigan_model.py",
    "synthesis/vocoders/hifigan.py",
]
